version: '3.4'

services:
  db:
    container_name: postgres-db-dev
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
       - ./db-data:/var/lib/postgresql/data
  
  api:
    container_name: xpendapi-dev
    depends_on:
      db:
        condition: service_healthy
    build:
      context: /be
      target: development
    volumes:
      - ./be:/app
      - /app/node_modules
    ports:
      - 5001:5001
    environment:
      NODE_ENV: development
      ORIGIN: ${ORIGIN}
      PORT: 5001
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD} 
      DB_NAME: ${DB_NAME}
      JWT_SECRET_PUBLIC: ${JWT_SECRET_PUBLIC}
      JWT_SECRET_PRIVATE: ${JWT_SECRET_PRIVATE}
  
    command: npm run start:dev 