name: Deploy to Heroku

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci, build and test
        run: |
          cd be
          npm ci
          npm run build --if-present
          npm test

  buildAndDeploy:
    runs-on: ubuntu-latest
    needs: test
    if: success() && github.ref == 'refs/heads/main'
    steps:
      - name: checkout source code
        uses: actions/checkout@v2
      - name: Deploy backend/server
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME_CLIENT}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
        env:
          HD_ORIGIN: ${{secrets.ORIGIN}}
          HD_DB_HOST: ${{secrets.DB_HOST}}
          HD_DB_NAME: ${{secrets.DB_NAME}}
          HD_DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          HD_DB_PORT: ${{secrets.DB_PORT}}
          HD_DB_USER: ${{secrets.DB_USER}}
          HD_NODE_ENV: ${{secrets.NODE_ENV}}
          HD_JWT_SECRET_PRIVATE: ${{secrets.JWT_SECRET_PRIVATE}}
          HD_JWT_SECRET_PUBLIC: ${{secrets.JWT_SECRET_PUBLIC}}
